
/* 
 Copyright (C) 2007 Ferdinando Ametrano
 Copyright (C) 2006 Eric Ehlers

 This file is part of QuantLib, a free-software/open-source library
 for financial quantitative analysts and developers - http://quantlib.org/

 QuantLib is free software: you can redistribute it and/or modify it
 under the terms of the QuantLib license.  You should have received a
 copy of the license along with this program; if not, please email
 <quantlib-dev@lists.sf.net>. The license is also available online at
 <http://quantlib.org/license.shtml>.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the license for more details.
*/

// Excel functions coded by hand, to be registered with Excel
// alongside the autogenerated functions.

#include <qlxl/functions/functioncount.hpp>
#include <ohxl/objecthandlerxl.hpp>

#define XLL_DEC DLLEXPORT


XLL_DEC long *qlFunctionCount() {
    static long returnValue = FUNCTION_COUNT;
    return &returnValue;
}

// Repository URL of the working copy:
// $WCURL$

//XLL_DEC long *qlInfoHighestRevisionNumber() {
//    static long returnValue = $WCREV$;
//    return &returnValue;
//}
//
//XLL_DEC char *qlInfoTimeStamp() {
//    char *date = "$WCDATE$";
//    return date;
//}
//
//#define MIXED_REVISIONS $WCMIXED?1:0$
//XLL_DEC char *qlInfoRevisionRange() {
//    #if MIXED_REVISIONS
//    #   pragma message(__FILE__ "() warning: mixed update revisions ($WCRANGE$)")
//    #endif
//    char *revRange = "$WCRANGE$";
//    return revRange;
//}
//
//#define LOCAL_MODIFICATION $WCMODS?1:0$
//XLL_DEC bool *qlInfoLocalModifications() {
//    #if LOCAL_MODIFICATION
//    #   pragma message(__FILE__ "() warning: local modifications have been found")
//    static bool result = true;
//    #else
//    static bool result = false;
//    #endif
//    return &result;
//}


#include <qlo/qladdindefines.hpp>
#include <oh/enumerations/typefactory.hpp>
#include <qlo/enumerations/factories/calendarfactory.hpp>
#include <ql/time/date.hpp>
#include <ql/time/calendar.hpp>
#include <qlo/loop/loop_calendar.hpp>
#include <ohxl/loop.hpp>

#include <ohxl/callingrange.hpp>
#include <qlxl/session.hpp>
#include <qlxl/conversions/all.hpp>

XLL_DEC OPER* qlCalendarHolidayList(
    char* Calendar,
    OPER* FromDate,
    OPER* ToDate,
    OPER* IncludeWeekEnds,
    OPER* Trigger) {

    // declare a shared pointer to the Function Call object

    boost::shared_ptr<ObjectHandler::FunctionCall> functionCall;

    try {

        // instantiate the Function Call object

        functionCall = boost::shared_ptr<ObjectHandler::FunctionCall>(
            new ObjectHandler::FunctionCall("qlCalendarHolidayList"));

        ObjectHandler::validateRange(Trigger, "Trigger");

        // initialize the session ID (if enabled)

        SET_SESSION_ID

            // convert input datatypes to C++ datatypes

            ObjectHandler::property_t FromDateCpp = ObjectHandler::convert2<ObjectHandler::property_t>(
                ObjectHandler::ConvertOper(*FromDate));

        ObjectHandler::property_t ToDateCpp = ObjectHandler::convert2<ObjectHandler::property_t>(
            ObjectHandler::ConvertOper(*ToDate));

        bool IncludeWeekEndsCpp = ObjectHandler::convert2<bool>(
            ObjectHandler::ConvertOper(*IncludeWeekEnds), "IncludeWeekEnds", false);

        // convert input datatypes to QuantLib datatypes

        QuantLib::Date FromDateLib = ObjectHandler::convert2<QuantLib::Date>(
            ObjectHandler::ConvertOper(*FromDate), "FromDate");

        QuantLib::Date ToDateLib = ObjectHandler::convert2<QuantLib::Date>(
            ObjectHandler::ConvertOper(*ToDate), "ToDate");

        // convert input datatypes to QuantLib enumerated datatypes

        QuantLib::Calendar CalendarEnum =
            ObjectHandler::Create<QuantLib::Calendar>()(Calendar);

        // invoke the utility function

        std::vector<QuantLib::Date> returnValue = CalendarEnum.holidayList(
            FromDateLib,
            ToDateLib,
            IncludeWeekEndsCpp);

        // convert and return the return value

        std::vector<long> returnValVec = QuantLibAddin::libraryToVector(returnValue);
        static OPER xRet;
        ObjectHandler::vectorToOper(returnValVec, xRet);
        return &xRet;

    }
    catch (const std::exception& e) {
        ObjectHandler::RepositoryXL::instance().logError(e.what(), functionCall);
        return 0;
    }
    catch (...) {
        ObjectHandler::RepositoryXL::instance().logError("unkown error type", functionCall);
        return 0;
    }

}
